### ISSUE TITLE
Non funziona!

### ISSUE THREAD

**Issue by grbasta** [lorenzo-deluca/homeassistant-traccar#1]
Anche rispettando alla lettera la guida mi dice che i dispositivi sono off Line eppure tutto configurato giusto

**Comment by lorenzo-deluca** [comment]
penso di aver risolto, era un problema sulla velocità, che nei cellulari non viene valorizzata.
Prova con la versione 0.2 e fammi sapere ;)

**Comment by grbasta** [comment]
![image](https://github.com/lorenzo-deluca/homeassistant-traccar/assets/46572022/404cd2ca-dac5-44c1-9b42-f8dc0e9897ce)

Purtroppo sono sempre in questa condizione, quindi sembrerebbe che traccar proprio non lo vede.

**Comment by lorenzo-deluca** [comment]
Hai aggiornato al mio ultimo script?
Purtroppo solo questo screen non dice niente, devi guardare i log di Home Assistant... io ti garantisco che funziona con l'app iOS di HA. eventualmente copiami qui il codice yaml del package modificato e gli do un occhio.

**Comment by grbasta** [comment]
#################################################################
#         Send Device Tracking status to TRACCAR Server
#################################################################
# Lorenzo De Luca ***@***.***)
# GitHub: https://github.com/lorenzo-deluca/homeassistant-traccar
# Version: 0.1
# * This program is distributed in the hope that it will be useful, but
WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# GNU Affero General Public License v3.0
#################################################################

rest_command:
  update_traccar:
    url: 'https://192.168.2.107:8082'
    method: GET
    payload:
'?id={{id}}&lat={{lat}}&lon={{lon}}&altitude={{alt}}&batt={{batt}}&speed={{speed}}'

automation:
  - id: 'position_tracking_update_traccar_position'
    alias: Position - Update Traccar Position
    description: ''
    trigger:
    - platform: state
      entity_id:
      - device_tracker.iphone_di_giovanni_basta
    condition:
    - condition: template
      value_template: '{{ trigger.from_state.state not in [''unknown'', ''
unavailable'']
        }}'
    - condition: template
      value_template: '{{ trigger.to_state.state not in [''unknown'', ''
unavailable'']
        }}'
    action:
    - service: rest_command.update_traccar
      continue_on_error: true
      data:
        id: '{{ trigger.entity_id }}'
        lat: '{{ state_attr(trigger.entity_id, ''latitude'')  | float(0) }}'
        lon: '{{ state_attr(trigger.entity_id, ''longitude'') | float(0) }}'
        alt: '{{ state_attr(trigger.entity_id, ''altitude'') | float(0) }}'
        batt: '{{ state_attr(trigger.entity_id, ''battery_level'') |
float(0) }}'
        speed: '0'
    mode: parallel
    max: 10



Il giorno ven 3 mag 2024 alle ore 15:13 Lorenzo ***@***.***>
ha scritto:

**Comment by lorenzo-deluca** [comment]
Sei sicuro che Traccar sia in ascolto in HTTPS sulla porta 8082?
La porta su cui inviare i dati non è quella della pagina web a cui ti colleghi.. di norma è la 5055 e va in HTTP, a meno che hai cambiato qualche configurazione.

**Comment by grbasta** [comment]
*risolto grazie*

Il giorno ven 3 mag 2024 alle ore 16:12 Lorenzo ***@***.***>
ha scritto:
