### ISSUE TITLE
Nivel de bateria

### ISSUE THREAD

**Issue by pilijic2** [lorenzo-deluca/homeassistant-traccar#10]
https://github.com/lorenzo-deluca/homeassistant-traccar/blame/27c7d5b7a88d7d7684f70dca4dafb1002d3af7d9/packages/traccar_positioning.yaml#L49

 selectattr('entity_id', 'match', '.*' ~ device_tracker.split('.')[1] ~ '_battery_level')

Agregar comodin antes del nombre hizo que el parametro de bateria funcionara correctamente para mi , anterior a eso no encontraba el sensor y retornaba valor cero.

Mi pento di non aver scritto in inglese o in italiano:)

**Comment by lorenzo-deluca** [comment]
Hello @pilijic2 , yes, it depends on the name of the battery level sensor, on the android and ios apps it was as I had defined it.
In any case a jolly at the beginning is not a problem 👍 

I added it to the new version 2024.12.1 ;)
