### ISSUE TITLE
Agradecimiento

### ISSUE THREAD

**Issue by pilijic2** [lorenzo-deluca/homeassistant-traccar#9]
Soy nuevo en ha y me ha sido dificil entender la logica de esto , pase dias para sencillamente hacer carpeta package y direccionar con !include :) :) .

Claramente voy a elogiar tu asistente traccar , funciona perfecto !! --- para hacerlo funcionar me obligo a aprender mas de HA y protocolo de traccar solo para darme cuenta todo estaba hecho y agregar un par de atributos mas como altitud y direccion es casi un copy/paste :)

El principal agradecimiento que te doy es que , con este codigo corto y simple ( simple estructuralmente y no desmerezco el estudio y conocimiento necesario ) , me ayudo a insertarme algo mas en la logica de HA , por ejemplo

{% for entity in states.device_tracker %}
   {% set dt = entity.entity_id  %}
   {% set latitud = state_attr( dt ,'latitude') %}
   {% set longitude = state_attr( dt ,'longitude') %}
   {% set accuracy = state_attr(dt,'gps_accuracy') %}
   {% set altitude = state_attr(dt,'altitude') %}
   {% set curse    = state_attr(dt,'course') %}
   {% set speed    = state_attr(dt,'speed') %}
   {% set climb    = state_attr(dt,'vertical_accuracy') %}
   {% set device = dt %}
   {{device}}
   {{latitud}}
   {{longitude}}
   {{accuracy}}
   {{altitude}}
   {{curse}}
   {{speed}}
   {{climb}}
{% endfor %}

Pensaba en buscar en cada elemento de device.tracker y enviar cuando en tu codigo pude darme cuenta que podia agregar cada dispositivo como lista , o mas aun , generar una etiqueta y enfocar el trigger a los miembros de la etiqueta ... un magnifico trabajo has realizado !!

Saludos desde Chile !!

**Comment by lorenzo-deluca** [comment]
Thanks a lot, your welcome ;)
If you want you can become a sponsor of my open source projects here on GitHub 👍 

Saluti dall'Italia
